#!/bin/sh

set -e

# Set default values for ENV's variables
export HOST=${HOST:-'ws://localhost:8546'}
export RATE_ENDPOINT=${RATE_ENDPOINT:-'http://localhost:65221/rate'}
export CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-'0x0000000000000000000000000000000000000008'}
export FROM_BLOCK=${FROM_BLOCK:-0}
export ORACLE_ADDRESS=${ORACLE_ADDRESS:-'0x6415CB729a27e9b69891dadaFcbBCae21e5B6F9C'}
export ORACLE_PK=${ORACLE_PK:-'0x4E805C7822DB4FC8BB15489D9C0497F2A939930DD85BA2817C234C7D507C844C'}

# Process config files
envsubst '${HOST} ${RATE_ENDPOINT} ${CONTRACT_ADDRESS} ${FROM_BLOCK} ${ORACLE_ADDRESS} ${ORACLE_PK}' < /app/config/config.docker.json > /app/config/config.json

# Start app
npm start