#!/bin/sh

set -e

# Set default values for ENV's variables
export HOST=${HOST:-'ws://localhost:8546'}
export RATE_ENDPOINT=${RATE_ENDPOINT:-'http://localhost:65221/rate'}
export CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-'0x0000000000000000000000000000000000000008'}
export FROM_BLOCK=${FROM_BLOCK:-0}
export ORACLE_ADDRESS=${ORACLE_ADDRESS:-'0x...'}
export ORACLE_PK=${ORACLE_PK:-'0x...'}
export GAS_PRICE=${GAS_PRICE:-'9000000000'}

# Process config files
envsubst '${HOST} ${RATE_ENDPOINT} ${CONTRACT_ADDRESS} ${FROM_BLOCK} ${ORACLE_ADDRESS} ${ORACLE_PK} ${GAS_PRICE}' < /app/config/config.docker.json > /app/config/config.json

# Start app
npm start