[parity]
chain = "sentinel.json"
base_path = "./base-path"
identity = "sentinel-node"

[ui]
force = true
port = 8180
interface = "127.0.0.1"

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[dapps]
disable = false

[network]
discovery = true
reserved_peers = "nodes.txt"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
