[parity]
chain = "sentinel.json"
identity = "sentinel-main"

[ui]
disable = true

[network]
discovery = true
reserved_peers = "nodes.txt"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
