[parity]
chain = "sentinel.json" #Sentinel Chain Genesis file
base_path = "./base"
identity = "sentinel-chain-node"

[ui]
disable = true

[network]
discovery = true
reserved_peers = "nodes.txt"

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"] #RPC functionality can be restricted

[footprint] # This config is needed for block explorers
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
