[parity]
chain = "sentinel.json"
identity = "sentinel-main"

[account]
unlock = ["0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"]
password = ["password.txt"]

[ui]
disable = true

[network]
discovery = true
reserved_peers = "nodes.txt"

[rpc]
interface = "local"
cors = ["*"]
hosts = ["all"]

[mining]
author = "0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"
engine_signer = "0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"
reseal_max_period = 300000

[footprint]
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
