[parity]
chain = "sentinel.json"
base_path = "./base-path"
identity = "sentinel-node"

[network]
discovery = true
reserved_peers = "nodes.txt"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
