[parity]
chain = "sentinel.json"
identity = "sentinel-validator"

[account]
unlock = ["ETH_ADDR"]
password = ["password-validator.txt"]

[ui]
disable = true

[network]
discovery = true
reserved_peers = "nodes.txt"

[mining]
author = "ETH_ADDR"
engine_signer = "ETH_ADDR"
reseal_max_period = 600000
min_gas_price = 8100000000 #min gas price in WEI per GAS unit (0.0000000081 Ether)
extra_data = "0x1" # Blocks that you mine will have '0x53' in extra data field.

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
