[parity]
chain = "sentinel.json" #Sentinel Chain Genesis file
base_path = "./base"
identity = "sentinel-chain-node"

[account]
unlock = ["0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"]
password = ["password.txt"]

[ui]
disable = true

[network]
discovery = true
reserved_peers = "nodes.txt"

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"] #RPC functionality can be restricted

[mining]
author = "0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"
engine_signer = "0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"
reseal_max_period = 30000

[footprint] # This config is needed for block explorers
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true