[parity]
chain = "genesis.json" #Sentinel Chain Genesis file

[account]
unlock = ["0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"]
password = ["password.txt"]

[ui]
force = false
disable = true #Nodes does not normally need Wallet UI

[network]
port = 30303
bootnodes = []
discovery = true

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"] #RPC functionality can be restricted

[mining]
author = "0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"
engine_signer = "0x574366e84f74f2e913ad9a6782ce6ac8022e16eb"
reseal_max_period = 30000

[footprint] # This config is needed for block explorers
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
