[parity]
chain = "sentinel.json"
identity = "sentinel-validator"

[account]
unlock = ["0x5925A1F91285C29af9E67CdFb52E89C04a3391cf"]
password = ["password-validator.txt"]

[ui]
disable = true

[network]
discovery = true
reserved_peers = "nodes.txt"

[mining]
author = "0x5925A1F91285C29af9E67CdFb52E89C04a3391cf"
engine_signer = "0x5925A1F91285C29af9E67CdFb52E89C04a3391cf"
reseal_max_period = 600000
min_gas_price = 100000000000000000 #min gas price in WEI per GAS unit (0.1 Ether)
extra_data = "0x1" # Blocks that you mine will have '0x53' in extra data field.

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
