#!/bin/sh

set -e

NODE_TYPE=${NODE_TYPE:-"default"}

if [ $NODE_TYPE = "default" ]; then
  NODE_TYPE=""
else
  NODE_TYPE="-$NODE_TYPE"
fi

/parity/parity --config ./config$NODE_TYPE.toml --base-path ./base-path $@