[parity]
chain = "sentinel.json"
identity = "sentinel-main"
no_persistent_txqueue = true

[account]
unlock = ["$UNLOCK"]
password = ["$PASS_PATH"]

[ui]
disable = true

[network]
discovery = true
reserved_peers = "$NODES_PATH"

[rpc]
interface = "local"
cors = ["*"]
hosts = ["all"]

[mining]
author = "$AUTHOR"
engine_signer = "$ENGINE_SIGNER"
reseal_max_period = 900000
min_gas_price = 8100000000 #min gas price in WEI per GAS unit (0.0000000081 Eth)

[footprint]
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "external_tx=debug,network=trace,own_tx=debug,poa=info,txqueue=debug"
log_file = "parity-main.log"
color = true
