[parity]
chain = "sentinel.json"
identity = "sentinel-validator"
no_persistent_txqueue = true

[account]
unlock = ["$UNLOCK"]
password = ["$PASS_PATH"]

[ui]
disable = true

[rpc]
interface = "all"

[network]
discovery = true
reserved_peers = "$NODES_PATH"

[mining]
author = "$AUTHOR"
engine_signer = "$ENGINE_SIGNER"
reseal_max_period = 900000
min_gas_price = 8100000000 #min gas price in WEI per GAS unit (0.0000000081 Ether)

[misc]
logging = "external_tx=debug,network=info,own_tx=debug,poa=info,txqueue=debug"
log_file = "parity-validator.log"
color = true



