[parity]
chain = "sentinel.json"
identity = "sentinel-main"

[account]
unlock = ["$UNLOCK"]
password = ["$PASS_PATH"]

[ui]
disable = true

[network]
discovery = true
reserved_peers = "$NODES_PATH"

[rpc]
interface = "local"
cors = ["*"]
hosts = ["all"]

[mining]
author = "$AUTHOR"
engine_signer = "$ENGINE_SIGNER"
reseal_max_period = 600000
min_gas_price = 1000000000000000 #min gas price in WEI per GAS unit (0.001 Ether)
extra_data = "0x0" # Blocks that you mine will have '0x53' in extra data field.

[footprint]
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true
