[parity]
chain = "sentinel.json"
identity = "sentinel-dev"

[ui]
disable = false
interface = "all"

[network]
discovery = true
reserved_peers = "$NODES_PATH"

[rpc]
interface = "all"
cors = ["*"]
hosts = ["all"]

[websockets]
interface = "all"
hosts = ["all"]
origins = ["all"]

[misc]
logging = "network=info,poa=debug,txqueue=debug"
log_file = "parity.log"
color = true