[parity]
chain = "sentinel.json"
identity = "sentinel-dev"

[ui]
disable = false
interface = "all"

[account]
password = ["$PASS_PATH"]

[network]
discovery = true
reserved_peers = "$NODES_PATH"

[rpc]
interface = "all"
cors = ["*"]
hosts = ["all"]

[websockets]
interface = "all"
hosts = ["all"]
origins = ["all"]

[mining]
author = "$AUTHOR"
engine_signer = "$ENGINE_SIGNER"
reseal_max_period = 600000
min_gas_price = 100000000000000000 #min gas price in WEI per GAS unit (0.1 Ether)
extra_data = "0x0" # Blocks that you mine will have '0x53' in extra data field.

[footprint]
tracing = "on"
fat_db = "on"
pruning = "archive"

[misc]
logging = "own_tx=trace"
log_file = "parity.log"
color = true