[parity]
chain = "sentinel.json"
identity = "sentinel-provider"

[dapps]
disable = true

[ui]
disable = true

[network]
port = $NETWORK_PORT
discovery = true
reserved_peers = "$NODES_PATH"

[rpc]
interface = "all"
cors = ["all"]
hosts = ["all"]
apis = ["safe"]

[websockets]
interface = "all"

[misc]
logging = "own_tx=trace"
log_file = "parity-rpc.log"
color = true
