#!/bin/sh

set -e

# Set default values for ENV's variables
export UNLOCK=${UNLOCK:-'0x...'}
export AUTHOR=${AUTHOR:-'0x...'}
export ENGINE_SIGNER=${ENGINE_SIGNER:-'0x...'}
export NETWORK_PORT=${NETWORK_PORT:-'30303'}
export PASS_PATH=${PASS_PATH:-'/sentinel/password.txt'}
export KEY_PATH=${KEY_PATH:-''}
export NODES_PATH=${NODES_PATH:-'/sentinel/nodes/nodes.txt'}

# Process config files
envsubst '${UNLOCK} ${AUTHOR} ${ENGINE_SIGNER} ${PASS_PATH} ${NODES_PATH}' < /sentinel/config/config-dev.docker.toml > /sentinel/config-dev.toml
envsubst '${NODES_PATH}' < /sentinel/config/config-main.docker.toml > /sentinel/config-main.toml
envsubst '${UNLOCK} ${AUTHOR} ${ENGINE_SIGNER} ${PASS_PATH} ${NODES_PATH}' < /sentinel/config/config-validator.docker.toml > /sentinel/config-validator.toml
envsubst '${NETWORK_PORT} ${NODES_PATH}' < /sentinel/config/config-provider.docker.toml > /sentinel/config-provider.toml
envsubst '${NODES_PATH}' < /sentinel/config/config-local.docker.toml > /sentinel/config-local.toml

# Import key
if [ ! -z $KEY_PATH ]; then
  /parity/parity account import $KEY_PATH --chain ./sentinel.json --keys-path ./base-path/keys
fi

# Process node type
NODE_TYPE=${NODE_TYPE:-"default"}
if [ $NODE_TYPE = "default" ]; then
  NODE_TYPE=""
else
  NODE_TYPE="-$NODE_TYPE"
fi

# Run parity
chown sentinel:sentinel -R /sentinel
/parity/parity --config ./config$NODE_TYPE.toml --base-path ./base-path $@