#!/bin/sh

set -e

# Set default values for ENV's variables
export NETWORK_PORT=${NETWORK_PORT:-'30303'}
export PASS_PATH=${PASS_PATH:-'/sentinel/password.txt'}
export KEY_PATH=${KEY_PATH:-''}
export NODES_PATH=${NODES_PATH:-'/sentinel/nodes/nodes.txt'}
export NODE_PUBKEY=${NODE_PUBKEY:-'0x...'}
export NODE_TYPE=${NODE_TYPE:-'dev'}

# Process config files
envsubst '${NODE_PUBKEY} ${PASS_PATH} ${NODES_PATH}' < /sentinel/config/config-dev.docker.toml > /sentinel/config-dev.toml
envsubst '${NODES_PATH}' < /sentinel/config/config-main.docker.toml > /sentinel/config-main.toml
envsubst '${NODE_PUBKEY} ${PASS_PATH} ${NODES_PATH}' < /sentinel/config/config-validator.docker.toml > /sentinel/config-validator.toml
envsubst '${NETWORK_PORT} ${NODES_PATH}' < /sentinel/config/config-provider.docker.toml > /sentinel/config-provider.toml
envsubst '${NODES_PATH}' < /sentinel/config/config-local.docker.toml > /sentinel/config-local.toml

# Import key
if [ ! -z $KEY_PATH ]; then
  /parity/parity account import $KEY_PATH --chain ./sentinel.json --keys-path ./base-path/keys
fi

# Check if nodes.txt not exists
if [ ! -f $NODES_PATH ]; then
    touch $NODES_PATH
fi

# Run parity
/parity/parity --config /sentinel/config-$NODE_TYPE.toml --base-path ./base-path $@